import type { VercelRequest,VercelResponse } from "@vercel/node";
const TOKEN=process.env.BOT_TOKEN||""; const ADMIN=String(process.env.ADMIN_TELEGRAM_ID||"831036378");
const SB_URL=process.env.SUPABASE_URL||""; const SB_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||""; const APP_URL=process.env.MINI_APP_URL||"";
async function tg(method:string,body:any){const r=await fetch(`https://api.telegram.org/bot${TOKEN}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});return r.json()}
async function db(path:string,init:any={}){const r=await fetch(`${SB_URL}/rest/v1/${path}`,{...init,headers:{apikey:SB_KEY,Authorization:`Bearer ${SB_KEY}`,"Content-Type":"application/json",...(init.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
const menu=(enabled=true)=>({inline_keyboard:[[{text:"📅 Открыть расписание",web_app:{url:APP_URL}}],[{text:enabled?"🔔 Уведомления: ВКЛ":"🔕 Уведомления: ВЫКЛ",callback_data:"toggle_notifications"}]]});
export default async function handler(req:VercelRequest,res:VercelResponse){try{if(req.method!=="POST")return res.status(200).json({ok:true});const u=req.body;const msg=u.message;const cb=u.callback_query;
 if(cb){const uid=String(cb.from.id);if(cb.data==="toggle_notifications"){const rows=await db(`notification_users?select=enabled&telegram_user_id=eq.${uid}`);const next=!Boolean(rows[0]?.enabled);await db(`notification_users?telegram_user_id=eq.${uid}`,{method:"PATCH",body:JSON.stringify({enabled:next,chat_id:cb.message.chat.id,updated_at:new Date().toISOString()})});if(!rows.length)await db("notification_users",{method:"POST",body:JSON.stringify({telegram_user_id:uid,chat_id:cb.message.chat.id,enabled:next})});await tg("answerCallbackQuery",{callback_query_id:cb.id,text:next?"Напоминания включены":"Напоминания выключены"});await tg("editMessageReplyMarkup",{chat_id:cb.message.chat.id,message_id:cb.message.message_id,reply_markup:menu(next)});return res.status(200).json({ok:true})}}
 if(!msg?.chat?.id)return res.status(200).json({ok:true});const uid=String(msg.from?.id||msg.chat.id);const text=String(msg.text||"");
 if(text.startsWith("/start")){await db("notification_users?on_conflict=telegram_user_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({telegram_user_id:uid,chat_id:msg.chat.id})}).catch(()=>{});const rows=await db(`notification_users?select=enabled&telegram_user_id=eq.${uid}`);await tg("sendMessage",{chat_id:msg.chat.id,text:"Привет! Здесь можно открыть расписание и включить напоминания за 10 минут до пары.",reply_markup:menu(rows[0]?.enabled!==false)});return res.status(200).json({ok:true})}
 if(text==="/notifications"){const rows=await db(`notification_users?select=enabled&telegram_user_id=eq.${uid}`);await tg("sendMessage",{chat_id:msg.chat.id,text:"Настройки напоминаний:",reply_markup:menu(rows[0]?.enabled!==false)});return res.status(200).json({ok:true})}
 if(text.startsWith("/broadcast")&&uid===ADMIN){const body=text.replace(/^\/broadcast\s*/i,"").trim();if(!body){await tg("sendMessage",{chat_id:msg.chat.id,text:"Использование: /broadcast текст сообщения"});return res.status(200).json({ok:true})}const users=await db("notification_users?select=chat_id&enabled=eq.true");for(const x of users){await tg("sendMessage",{chat_id:x.chat_id,text:`📢 ${body}`}).catch(()=>{})}await tg("sendMessage",{chat_id:msg.chat.id,text:`Готово. Отправлено: ${users.length}`});return res.status(200).json({ok:true})}
 if(text==="/admin"&&uid===ADMIN){await tg("sendMessage",{chat_id:msg.chat.id,text:"Админ: /broadcast текст — отправить сообщение всем, кто включил уведомления."});return res.status(200).json({ok:true})}
 await tg("sendMessage",{chat_id:msg.chat.id,text:"Используй кнопки ниже.",reply_markup:menu(true)});return res.status(200).json({ok:true});
 }catch(e){return res.status(200).json({ok:false})}}
